### ISSUE TITLE
integration with Grammar project (input and parameters, output)

### ISSUE THREAD

**Issue by fazleh2010** [ag-sc/QueGG-web#1]
--A description of all parameters to this call (what are they, do they need external files, ...?) and input and output as follow:
 
java -jar target/QuestionGrammarGenerator.jar EN lexicon/en output 100 ttl

1) args[0]: EN (generating English grammar. DE  for generating German Grammar)
2) args[1]: lexicon/en (the folder of input files. the folder contains .ttl file or .csv file. 
3) args[2]: output (where it generates JSON files. JSON files contains the description of grammar rules and entity list which is call binding list)
4) args[3]: 100 (number of entities). For example, what is the birthplace of X (X is the number of entities res:Donald_Trump, res:Angela_Merkel, etc.)
5)args[4]: ttl (it is an indicator of types of input file. If the input files are lemon, then the parameter is ttl. If the input file is csv (Google Sheet) if is it csv file)
All the parameters are necessary for the grammar project only.

Input:
The example of input [folder] (https://github.com/fazleh2010/question-grammar-generator/tree/extension/examples/input/lexicon/en/nouns)
a) An example of .ttl file can be found  [here] (https://github.com/fazleh2010/question-grammar-generator/blob/extension/examples/input/lexicon/en/nouns/lexicon-birthPlace_of.ttl)
b) An example of .csv file can be found  [here] (https://github.com/fazleh2010/question-grammar-generator/blob/extension/examples/input/lexicon/en/nouns/NounPPFrame%20-%20QALD%20Train%20-%20not%20solved.csv). These are files we see in the google XSL sheets and mention in the paper.

output:
 csv file can be found  [here] (https://github.com/fazleh2010/question-grammar-generator/blob/extension/examples/output/questions.csv). The csv file I have been sending to you so far. it is as same as the one that is in /tmp/ for your application

**Comment by FrankGrimm** [comment]
I'll close this since we implemented all of this.
